// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// DBConnectionInterface is an autogenerated mock type for the DBConnectionInterface type
type DBConnectionInterface struct {
	mock.Mock
}

// GetMongoObject provides a mock function with given fields:
func (_m *DBConnectionInterface) GetMongoObject() *mongo.Client {
	ret := _m.Called()

	var r0 *mongo.Client
	if rf, ok := ret.Get(0).(func() *mongo.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Client)
		}
	}

	return r0
}
