// Code generated by go-swagger; DO NOT EDIT.

// Package restapi API Specification for IMDB service.
//
//  API Specification for IMDB service.
//  Schemes:
//    http
//  Host: localhost:7777
//  BasePath: /v1
//  Version: 1.0.0
//  License: MIT https://github.com/vibhordubey333
//  Contact: <vibhordubey333@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
