// Code generated by go-swagger; DO NOT EDIT.

package add_movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"MoviesDB/models"
)

// AddRatingOKCode is the HTTP code returned for type AddRatingOK
const AddRatingOKCode int = 200

/*AddRatingOK Rating added successfully.

swagger:response addRatingOK
*/
type AddRatingOK struct {

	/*
	  In: Body
	*/
	Payload *AddRatingOKBody `json:"body,omitempty"`
}

// NewAddRatingOK creates AddRatingOK with default headers values
func NewAddRatingOK() *AddRatingOK {

	return &AddRatingOK{}
}

// WithPayload adds the payload to the add rating o k response
func (o *AddRatingOK) WithPayload(payload *AddRatingOKBody) *AddRatingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add rating o k response
func (o *AddRatingOK) SetPayload(payload *AddRatingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRatingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddRatingInternalServerErrorCode is the HTTP code returned for type AddRatingInternalServerError
const AddRatingInternalServerErrorCode int = 500

/*AddRatingInternalServerError Server Error

swagger:response addRatingInternalServerError
*/
type AddRatingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddRatingInternalServerError creates AddRatingInternalServerError with default headers values
func NewAddRatingInternalServerError() *AddRatingInternalServerError {

	return &AddRatingInternalServerError{}
}

// WithPayload adds the payload to the add rating internal server error response
func (o *AddRatingInternalServerError) WithPayload(payload *models.Error) *AddRatingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add rating internal server error response
func (o *AddRatingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRatingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddRatingDefault error

swagger:response addRatingDefault
*/
type AddRatingDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddRatingDefault creates AddRatingDefault with default headers values
func NewAddRatingDefault(code int) *AddRatingDefault {
	if code <= 0 {
		code = 500
	}

	return &AddRatingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add rating default response
func (o *AddRatingDefault) WithStatusCode(code int) *AddRatingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add rating default response
func (o *AddRatingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add rating default response
func (o *AddRatingDefault) WithPayload(payload *models.Error) *AddRatingDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add rating default response
func (o *AddRatingDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRatingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
