// Code generated by go-swagger; DO NOT EDIT.

package ratemovies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MoviesratingHandlerFunc turns a function with the right signature into a moviesrating handler
type MoviesratingHandlerFunc func(MoviesratingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MoviesratingHandlerFunc) Handle(params MoviesratingParams) middleware.Responder {
	return fn(params)
}

// MoviesratingHandler interface for that can handle valid moviesrating params
type MoviesratingHandler interface {
	Handle(MoviesratingParams) middleware.Responder
}

// NewMoviesrating creates a new http.Handler for the moviesrating operation
func NewMoviesrating(ctx *middleware.Context, handler MoviesratingHandler) *Moviesrating {
	return &Moviesrating{Context: ctx, Handler: handler}
}

/*Moviesrating swagger:route GET /imdbservice/moviesrating ratemovies moviesrating

Movies rated by a user.

Movies rated by a user.

*/
type Moviesrating struct {
	Context *middleware.Context
	Handler MoviesratingHandler
}

func (o *Moviesrating) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMoviesratingParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// MoviesratingBody moviesrating body
//
// swagger:model MoviesratingBody
type MoviesratingBody struct {

	// Movie name.
	MovieName string `json:"MovieName,omitempty"`

	// Movie rating.
	UserName string `json:"UserName,omitempty"`
}

// Validate validates this moviesrating body
func (o *MoviesratingBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MoviesratingBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MoviesratingBody) UnmarshalBinary(b []byte) error {
	var res MoviesratingBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// MoviesratingOKBodyItems0 moviesrating o k body items0
//
// swagger:model MoviesratingOKBodyItems0
type MoviesratingOKBodyItems0 struct {

	// Comments given on the movie by user.
	Comments string `json:"comments,omitempty"`

	// Name of the movie.
	MovieName string `json:"movieName,omitempty"`

	// Rating of the movie.
	Rating string `json:"rating,omitempty"`
}

// Validate validates this moviesrating o k body items0
func (o *MoviesratingOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MoviesratingOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MoviesratingOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res MoviesratingOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
