// Code generated by go-swagger; DO NOT EDIT.

package add_comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddCommentsHandlerFunc turns a function with the right signature into a add comments handler
type AddCommentsHandlerFunc func(AddCommentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddCommentsHandlerFunc) Handle(params AddCommentsParams) middleware.Responder {
	return fn(params)
}

// AddCommentsHandler interface for that can handle valid add comments params
type AddCommentsHandler interface {
	Handle(AddCommentsParams) middleware.Responder
}

// NewAddComments creates a new http.Handler for the add comments operation
func NewAddComments(ctx *middleware.Context, handler AddCommentsHandler) *AddComments {
	return &AddComments{Context: ctx, Handler: handler}
}

/*AddComments swagger:route POST /imdbservice/addcomment addComment addComments

Add movie into DB.

Add movie into DB.

*/
type AddComments struct {
	Context *middleware.Context
	Handler AddCommentsHandler
}

func (o *AddComments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddCommentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddCommentsBody add comments body
//
// swagger:model AddCommentsBody
type AddCommentsBody struct {

	// Comment for movie.
	MovieComment string `json:"MovieComment,omitempty"`

	// Movie name.
	MovieName string `json:"MovieName,omitempty"`
}

// Validate validates this add comments body
func (o *AddCommentsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddCommentsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddCommentsBody) UnmarshalBinary(b []byte) error {
	var res AddCommentsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// AddCommentsOKBody add comments o k body
//
// swagger:model AddCommentsOKBody
type AddCommentsOKBody struct {

	// Response Code
	Code string `json:"code,omitempty"`

	// Comment addded message.
	Message string `json:"message,omitempty"`
}

// Validate validates this add comments o k body
func (o *AddCommentsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddCommentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddCommentsOKBody) UnmarshalBinary(b []byte) error {
	var res AddCommentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
